# Generated by Django 5.2.4 on 2026-04-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_is_active_product_seller_product_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('code', 'Code'), ('paper', 'Papers'), ('project', 'Projects'), ('internship', 'Internships'), ('other', 'Other Academic Resource')], default='code', max_length=20),
        ),
    ]
