from django.urls import path
from .views import (
    admin_dashboard,
    ProductDetailView,
    ProductListView,
    add_to_cart,
    buyer_orders_view,
    cart_view,
    category_products,
    checkout_view,
    order_confirmation,
    product_status_api,
    profile_view,
    register_view,
    remove_cart_item,
    seller_dashboard,
    seller_orders_view,
    seller_product_create,
    seller_product_delete,
    seller_product_edit,
    search_products,
    update_cart_item,
)

urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('admin-panel/', admin_dashboard, name='admin_dashboard'),
    path('products/', ProductListView.as_view(), name='product_list'),
    path('products/<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('category/<slug:slug>/', category_products, name='product_by_category'),
    path('search/', search_products, name='search_products'),
    path('register/', register_view, name='register'),
    path('profile/', profile_view, name='profile'),
    path('cart/', cart_view, name='cart'),
    path('cart/add/<slug:slug>/', add_to_cart, name='add_to_cart'),
    path('cart/update/<int:item_id>/', update_cart_item, name='update_cart_item'),
    path('cart/remove/<int:item_id>/', remove_cart_item, name='remove_cart_item'),
    path('checkout/', checkout_view, name='checkout'),
    path('order/confirmation/<int:order_id>/', order_confirmation, name='order_confirmation'),
    path('orders/', buyer_orders_view, name='buyer_orders'),
    path('seller/dashboard/', seller_dashboard, name='seller_dashboard'),
    path('seller/products/add/', seller_product_create, name='seller_product_create'),
    path('seller/products/<slug:slug>/edit/', seller_product_edit, name='seller_product_edit'),
    path('seller/products/<slug:slug>/delete/', seller_product_delete, name='seller_product_delete'),
    path('seller/orders/', seller_orders_view, name='seller_orders'),
    path('api/products/<slug:slug>/status/', product_status_api, name='product_status_api'),
]
